# Generated by Django 3.2.9 on 2022-06-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='schoolinfo',
            options={'verbose_name': 'Информация о школе', 'verbose_name_plural': 'Информация о школе'},
        ),
        migrations.AddField(
            model_name='sociallink',
            name='awesome_class',
            field=models.CharField(max_length=100, null=True, verbose_name='Awesome'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='background_image',
            field=models.ImageField(upload_to='school_info/', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='school_image',
            field=models.ImageField(upload_to='school_info/', verbose_name='Фото школы'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Изображение'),
        ),
    ]
