# Generated by Django 3.2.9 on 2022-06-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_timetable_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_time', to='lessons.shiftnumber', verbose_name='Номер смены'),
        ),
    ]
