# Generated by Django 3.2.9 on 2022-06-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_timetable_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='shift',
        ),
    ]
